name: Feature request
description: Suggest an idea or enhancement for YNCLI
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thank you for suggesting a new idea for YNCLI!
  - type: textarea
    id: feature-description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
